### ISSUE TITLE
original origin is unmantained

### ISSUE THREAD

**Issue by loop23** [yourabi/twitter-typeahead-rails#21]
Hello,
Thanks for the gem but.. after experiencing some problems (namely, if I searched something like "pollina" it would display results at "polli", nothing at "pollin" and yet again something at "pollina"), after some research I found out that the original repo is unmantained, while work resumed at https://github.com/corejavascript/typeahead.js

I urgently needed the fixes, so I forked your repo here: https://github.com/loop23/twitter-typeahead-rails and included the mantained upstream.

Are you still mantaining the gem? if so I can make a PR

Bye

**Comment by yourabi** [comment]
Please do send a PR.

**Comment by loop23** [comment]
I have. A while ago. Please just accept the PR, the world will be a slightly (very slightly) better place!

**Comment by yourabi** [comment]
Closing since the PR is merged
