### ISSUE TITLE
Missing CSS

### ISSUE THREAD

**Issue by demetrios** [yourabi/twitter-typeahead-rails#4]
Am I missing something or is the CSS missing from this gem?

I needed to included [this](https://github.com/jharding/typeahead.js-bootstrap.css/blob/master/typeahead.js-bootstrap.css) to get the interface to look ok.

**Comment by techbrownbags** [comment]
@s01ipsist & @yourabi  thank you thank you thank you! 

I haven't spent much time on this thanks to you!

maybe add this to the README?

**Comment by frank184** [comment]
#24
